#!/bin/bash
#
# DESCRIPTION
# ------------------------------------------------------------
# c_test is a command line tool that asserts the output of an executable 
# against expected output. The program to test and the expected output
# are passed as arguments to the c_test script. c_test can handle programs
# that themselves take command line arguments. See USAGE for the details.
#
# If the asserted output is the same as the actual output, the test passes.
# If the asserted output is not the same as the actual output, the test fails
# and prints a comparison of the outputs.
#
# USAGE
# ------------------------------------------------------------
#
# c_test {program under test} {args}* {expected output}
# *: args is optional.
# 
#
# Testing a program that takes arguments:
#
#	c_test sum 3 4 7
#    	Testing sum(3 4) == 7...
#    	PASSED.
#
# Testing a program that takes NO arguments:
#
#	c_test hello_world hello_world.test_that_prints_hello_world
#       Testing hello_world() == 'Hello world!'
#	PASSED.
#
# ------------------------------------------------------------


# A test should be provided with 1) a program to test and b)
# its expected output. 
if [ "$#" -lt 2 ]; then
    echo "Usage: $0 program [arg1 arg2 ...] expected_output"
    exit 1
fi

# Arrange.
program=$1
shift 

if [ ! -t 0 ]; then
	expected_output="$(cat)"
	args=("$@")
else
	expected_output="${@: -1}"
	args=("${@:1:$#-1}")
fi

# Act.
output=$(./"$program" "${args[@]}")

# Assert.
if [[ "$output" == "$expected_output" ]]; then
    echo "PASS"
else
    echo "FAIL"
    echo "--------output----------"
    echo "$output"
    echo "-------expected---------"
    echo "$expected_output"
fi
